version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - nps_data:/var/lib/postgresql/data
  
  # nextjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #   environment:
  #     - NODE_ENV=development

volumes:
  nps_data:
    driver: local