import "@/styles/globals.css";
import Providers from "@/utils/Provider";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true} className={rubik.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
